"""Read and write the per-branch package manifests.

A manifest names the exact version of every package a branch should carry.
It is the desired state: promotion reconciles the bucket to it rather than
being told which packages to copy, so the branch contents are reviewable
in git and reproducible from the file alone.
"""

import pathlib

import yaml

MANIFEST_DIR = "branches"
HEADER = """\
# Packages this branch carries, and at which version.
#
# Generated by the promotion-proposal workflow and applied on merge:
# editing a version here promotes, removing an entry withdraws the package.
"""


def path_for(branch: str, root: str = ".") -> pathlib.Path:
    return pathlib.Path(root) / MANIFEST_DIR / f"{branch}.yml"


def load(branch: str, root: str = ".") -> dict[str, str]:
    p = path_for(branch, root)
    if not p.exists():
        return {}
    return yaml.safe_load(p.read_text()).get("packages") or {}


def dump(branch: str, packages: dict[str, str], root: str = ".") -> str:
    body = "".join(f"  {n}: {v}\n" for n, v in sorted(packages.items()))
    return f"{HEADER}\npackages:\n{body}" if packages else f"{HEADER}\npackages: {{}}\n"


def save(branch: str, packages: dict[str, str], root: str = ".") -> None:
    p = path_for(branch, root)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(dump(branch, packages, root))
